apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-api
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-api
  template:
    metadata:
      labels:
        app: account-api
    spec:
      containers:
        - name: account-api
          image: your-docker-username/account-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: cassandra-config
            - secretRef:
                name: cassandra-secrets
          env:
            - name: CASSANDRA_HOST
              value: "cassandra.db.svc.cluster.local"