version: '3.9'

services:
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=8080
    expose:
      - "8080"
    networks:
      - app-network

  auth-service:
    build: 
      context: ./backend/auth-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - FIREBASE_SERVICE_ACCOUNT=${FIREBASE_SERVICE_ACCOUNT}
    depends_on:
      - redis
    networks:
      - app-network

  canvas-backend:
    build:
      context: ./backend/canvas-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PORT=8081
      - MONGODB_URI=mongodb://mongodb:27017/canvas_app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_AUTH_URL=${VITE_AUTH_URL}
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
      - auth-service
      - canvas-backend
    networks:
      - app-network

  load-balancer:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
      - auth-service
      - frontend
      - canvas-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
  mongodb_data: