apiVersion: v1
kind: Namespace
metadata:
  name: nginx-namespace

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-api-gateway
  namespace: nginx-namespace
spec:
  type: LoadBalancer
  ports:
    - port: 8000          # HTTP port exposed externally
      targetPort: 8000    # Port used by the NGINX container
  selector:
    app: nginx-api-gateway

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx-namespace
data:
  default.conf: |
    server {
        listen 8000;

        # Global CORS headers
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;

        # Route to account-api
        location /account/ {
            rewrite ^/account(/.*)$ $1 break;
            proxy_pass http://account-api.backend.svc.cluster.local:8080; # Remove trailing slash
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Route to canvas-api
        location /canvas/ {
            rewrite ^/canvas(/.*)$ $1 break;  # Rewrite to remove the /canvas prefix
            proxy_pass http://canvas-api.backend.svc.cluster.local:8080; # Remove trailing slash
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Health check endpoint
        location /health {
            access_log off;
            return 200 "API Gateway is healthy\n";
            add_header Content-Type text/plain;
        }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-api-gateway
  namespace: nginx-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-api-gateway
  template:
    metadata:
      labels:
        app: nginx-api-gateway
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
