apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: db
spec:
  replicas: 2
  serviceName: "cassandra"
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      initContainers:
        - name: set-vm-max-map-count
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=1048575"]
          securityContext:
            privileged: true  # Required to modify kernel parameters
      containers:
        - name: cassandra
          image: cassandra:5.0.0  # Latest version
          ports:
            - containerPort: 9042  # CQL
            - containerPort: 7000  # Internode communication
            - containerPort: 7199  # JMX monitoring (optional)
            - containerPort: 7001  # SSL internode communication (optional)
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: "CassandraCluster"
            - name: CASSANDRA_SEEDS
              value: "cassandra-0.cassandra.db.svc.cluster.local"
            - name: CASSANDRA_LISTEN_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP  # Each pod will use its own IP
            - name: CASSANDRA_BROADCAST_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP  # Broadcast own IP to other nodes
            - name: CASSANDRA_BROADCAST_RPC_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP  # Same as above for RPC communication
            - name: CASSANDRA_RPC_ADDRESS
              value: 0.0.0.0  # Allows all interfaces for RPC
            - name: MAX_HEAP_SIZE
              value: "2g"
            - name: HEAP_NEWSIZE
              value: "512M"
            - name: CASSANDRA_COMMITLOG_DIRECTORY
              value: "/dev/null"  # This disables commit log writes
            - name: JVM_OPTS
              value: "-Dcassandra.commitlog_total_space=0 -Dcassandra.commitlog_sync=false"
            - name: CASSANDRA_DISABLE_COMMITLOG
              value: "true"  # Disable commit log entirely
          resources:
            requests:
              memory: "4Gi"  # Increased memory request
              cpu: "500m"
            limits:
              memory: "8Gi"  # Increased memory limit
              cpu: "2"
          securityContext:
            capabilities:
              add:
                - SYS_RESOURCE  # Required to set memlock and other system limits
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi  # Increased storage request to ensure no issues with OOM
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: db
spec:
  clusterIP: None  # Necessary for StatefulSet headless service
  selector:
    app: cassandra
  ports:
    - name: cql
      port: 9042
      targetPort: 9042
    - name: internode
      port: 7000
      targetPort: 7000
    - name: jmx
      port: 7199
      targetPort: 7199
    - name: ssl-internode
      port: 7001
      targetPort: 7001
