apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-data
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard
