apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-schema-apply
  namespace: db
spec:
  template:
    metadata:
      name: cassandra-schema-apply
    spec:
      containers:
        - name: cassandra-schema
          image: cassandra:3.11.10
          command:
            - sh
            - -c
            - |
              # Wait for Cassandra to be ready
              until cqlsh cassandra-0.cassandra.db.svc.cluster.local 9042 -e 'DESCRIBE KEYSPACES'; do
                echo 'Waiting for Cassandra to be ready...';
                sleep 5;
              done;

              # Log the keyspaces before applying the schema
              echo "Existing keyspaces before schema application:";
              cqlsh cassandra-0.cassandra.db.svc.cluster.local 9042 -e 'DESCRIBE KEYSPACES';

              # Apply the schema
              echo "Applying the schema...";
              cqlsh cassandra-0.cassandra.db.svc.cluster.local 9042 -f /schema/schema.cql;

              # Log the keyspaces again after applying the schema
              echo "Existing keyspaces after schema application:";
              cqlsh cassandra-0.cassandra.db.svc.cluster.local 9042 -e 'DESCRIBE KEYSPACES';
          volumeMounts:
            - name: schema-volume
              mountPath: /schema
      restartPolicy: OnFailure
      volumes:
        - name: schema-volume
          configMap:
            name: cassandra-schema  # Ensure the schema.cql file is in this ConfigMap
  backoffLimit: 4  # Limit retries in case of failure
