apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: db
spec:
  clusterIP: None  # Ensures each pod gets its own DNS name for peer discovery
  selector:
    app: cassandra
  ports:
    - name: cql
      port: 9042
      targetPort: 9042

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: db
spec:
  replicas: 2  # Update this to scale the cluster
  serviceName: "cassandra"
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:3.11.10
          ports:
            - containerPort: 9042  # CQL port
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: "CassandraCluster"  # Define a cluster name
            - name: CASSANDRA_SEEDS
              value: "cassandra-0.cassandra.db.svc.cluster.local"
            - name: CASSANDRA_LISTEN_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP  # Use Pod IP for intra-cluster communication
            - name: CASSANDRA_BROADCAST_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CASSANDRA_BROADCAST_RPC_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
          readinessProbe:
            exec:
              command: ["cqlsh", "-e", "describe keyspaces"]
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
