apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: db
spec:
  containers:
    - name: debug
      image: nicolaka/netshoot
      command: ["/bin/bash", "-c", "while true; do sleep 30; done;"]
