apiVersion: apps/v1
kind: Deployment
metadata:
  name: canvas-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canvas-api
  template:
    metadata:
      labels:
        app: canvas-api
    spec:
      containers:
      - name: canvas-api
        image: canvas-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 6969
        env:
        - name: CANVAS_API_PORT
          value: "6969"
        - name: CASSANDRA_HOST
          value: "cassandra"
        - name: CASSANDRA_PORT
          value: "9042"
        - name: CASSANDRA_KEYSPACE
          value: "myapp_dev"
        - name: CASSANDRA_USERNAME
          value: "cassandra"
        - name: CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CASSANDRA_PASSWORD
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REDIS_PASSWORD
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
---
apiVersion: v1
kind: Service
metadata:
  name: canvas-api
spec:
  selector:
    app: canvas-api
  ports:
    - protocol: TCP
      port: 6969
      targetPort: 6969