apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-api
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-api
  template:
    metadata:
      labels:
        app: account-api
    spec:
      containers:
        - name: account-api
          image: account-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: cassandra-config        # Cassandra ConfigMap
            - configMapRef:
                name: redis-config            # Redis ConfigMap
            - configMapRef:
                name: cognito-config          # AWS Cognito ConfigMap
            - secretRef:
                name: cassandra-secrets       # Cassandra Secret
            - secretRef:
                name: backend-redis-secret    # Redis Secret
            - secretRef:
                name: cognito-secret          # AWS Cognito Secret
            - secretRef:
                name: jwt-secret              # JWT Secret
          env:
            # Cassandra environment variables
            - name: CASSANDRA_HOST
              value: "cassandra.db.svc.cluster.local"
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra-secrets
                  key: CASSANDRA_PASSWORD

            # Redis environment variables for Authentication
            - name: AUTH_REDIS_HOST
              value: "redis.backend.svc.cluster.local"
            - name: AUTH_REDIS_PORT
              value: "6379"
            - name: AUTH_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-redis-secret
                  key: REDIS_PASSWORD

            # Cognito environment variables
            - name: COGNITO_USER_POOL_ID
              valueFrom:
                configMapKeyRef:
                  name: cognito-config
                  key: COGNITO_USER_POOL_ID
            - name: COGNITO_APP_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: cognito-config
                  key: COGNITO_APP_CLIENT_ID
            - name: COGNITO_APP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cognito-secret
                  key: COGNITO_APP_CLIENT_SECRET
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: cognito-secret
                  key: AWS_REGION

            # JWT Secret environment variable
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY

          imagePullPolicy: IfNotPresent
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: account-api
  namespace: backend
spec:
  selector:
    app: account-api
  ports:
    - protocol: TCP
      port: 8080           # Service port
      targetPort: 8080     # Container port
  type: ClusterIP          # Default service type, accessible within the cluster
