apiVersion: apps/v1
kind: Deployment
metadata:
  name: canvas-api
  namespace: backend  # Ensure the correct namespace is used
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canvas-api
  template:
    metadata:
      labels:
        app: canvas-api
    spec:
      containers:
        - name: canvas-api
          image: canvas-api:latest  # Use your built Docker image
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: cassandra-config        # Cassandra ConfigMap
            - configMapRef:
                name: redis-config            # Redis ConfigMap
            - configMapRef:
                name: cognito-config          # AWS Cognito ConfigMap
            - secretRef:
                name: cassandra-secrets       # Cassandra Secret
            - secretRef:
                name: backend-redis-secret    # Redis Secret
            - secretRef:
                name: cognito-secret          # AWS Cognito Secret
            - secretRef:
                name: jwt-secret              # JWT Secret
          env:
            - name: CASSANDRA_HOST
              value: "cassandra.db.svc.cluster.local"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-redis-secret
                  key: REDIS_PASSWORD
            - name: COGNITO_USER_POOL_ID
              valueFrom:
                configMapKeyRef:
                  name: cognito-config
                  key: COGNITO_USER_POOL_ID
            - name: COGNITO_APP_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: cognito-config
                  key: COGNITO_APP_CLIENT_ID
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: canvas-api
  namespace: backend  # Ensure it is in the correct namespace
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: canvas-api  # This must match the app label in the Deployment
