apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-drawing
  namespace: redis-drawing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-drawing
  template:
    metadata:
      labels:
        app: redis-drawing
    spec:
      containers:
        - name: redis
          image: redis:7.0  # Use appropriate Redis version
          ports:
            - containerPort: 6379
          env:
            - name: DRAWING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drawing-redis-secret  # Referencing the drawing-redis-secret
                  key: REDIS_PASSWORD
          args: ["--requirepass", "$(DRAWING_REDIS_PASSWORD)"]  # Use dynamic password from environment variable
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}  # Or you can use a PersistentVolumeClaim if needed
---
apiVersion: v1
kind: Service
metadata:
  name: redis-drawing
  namespace: redis-drawing
spec:
  selector:
    app: redis-drawing
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  clusterIP: None
